export const STUDIO_ERROR_CODES = [
  "STUDIO_SESSION_INVALID",
  "STUDIO_ORIGIN_REJECTED",
  "STUDIO_REQUEST_TOO_LARGE",
  "STUDIO_REQUEST_INVALID",
  "STUDIO_DRAFT_NOT_FOUND",
  "STUDIO_DRAFT_CONFLICT",
  "STUDIO_DRAFT_INVALID",
  "STUDIO_ASSET_INVALID",
  "STUDIO_IMPORT_INVALID",
  "STUDIO_EXPORT_INVALID",
  "STUDIO_DELETE_FAILED",
  "STUDIO_SAVE_FAILED",
  "STUDIO_APPLY_FAILED",
  "RUNTIME_STATUS_UNAVAILABLE",
  "INTERNAL",
] as const;

export type StudioErrorCode = typeof STUDIO_ERROR_CODES[number];

export const STUDIO_ERROR_HTTP_STATUS: Readonly<Record<StudioErrorCode, number>> = {
  STUDIO_SESSION_INVALID: 401,
  STUDIO_ORIGIN_REJECTED: 403,
  STUDIO_REQUEST_TOO_LARGE: 413,
  STUDIO_REQUEST_INVALID: 400,
  STUDIO_DRAFT_NOT_FOUND: 404,
  STUDIO_DRAFT_CONFLICT: 409,
  STUDIO_DRAFT_INVALID: 422,
  STUDIO_ASSET_INVALID: 422,
  STUDIO_IMPORT_INVALID: 422,
  STUDIO_EXPORT_INVALID: 422,
  STUDIO_DELETE_FAILED: 422,
  STUDIO_SAVE_FAILED: 422,
  STUDIO_APPLY_FAILED: 409,
  RUNTIME_STATUS_UNAVAILABLE: 503,
  INTERNAL: 500,
};

export class StudioError extends Error {
  constructor(
    public readonly code: StudioErrorCode,
    message: string,
    public readonly nextAction?: string,
  ) {
    super(message);
    this.name = "StudioError";
  }
}
