import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

interface ThemeCLIContractShape {
  readonly contractVersion?: unknown;
  readonly protocolVersion?: unknown;
  readonly themeSchemaVersion?: unknown;
  readonly limits?: {
    readonly themeJsonBytes?: unknown;
    readonly archiveBytes?: unknown;
    readonly imageBytes?: unknown;
  };
}

const contractPath = "contracts/theme-cli/v1/contract.json";
const generatedPath = "host/go/internal/themecli/contract_generated.go";

function positiveInteger(value: unknown, name: string): number {
  if (!Number.isSafeInteger(value) || (value as number) < 1) {
    throw new Error(`Theme CLI contract ${name} must be a positive integer`);
  }
  return value as number;
}

export async function generateGoThemeContract(workspaceRootInput: string): Promise<string> {
  const workspaceRoot = resolve(workspaceRootInput);
  const contractText = await readFile(resolve(workspaceRoot, contractPath), "utf8");
  if (contractText.includes("`")) {
    throw new Error("Theme CLI contract cannot contain a Go raw-string delimiter");
  }
  const contract = JSON.parse(contractText) as ThemeCLIContractShape;
  if (contract.contractVersion !== 1 || contract.protocolVersion !== 1 || contract.themeSchemaVersion !== 4) {
    throw new Error("Theme CLI contract versions are invalid");
  }
  const themeJsonBytes = positiveInteger(contract.limits?.themeJsonBytes, "themeJsonBytes");
  const archiveBytes = positiveInteger(contract.limits?.archiveBytes, "archiveBytes");
  const imageBytes = positiveInteger(contract.limits?.imageBytes, "imageBytes");
  const normalizedContract = `${contractText.trimEnd()}\n`;
  return `// Code generated by scripts/build-go-theme-contract.ts; DO NOT EDIT.\n\npackage themecli\n\nconst (\n\tmaxThemeJSONBytes  int64 = ${themeJsonBytes}\n\tmaxArchiveBytes    int64 = ${archiveBytes}\n\tmaxThemeImageBytes int64 = ${imageBytes}\n)\n\nconst themeCLIContractJSON = \`${normalizedContract}\`\n`;
}

export async function writeGoThemeContract(workspaceRootInput: string): Promise<void> {
  const workspaceRoot = resolve(workspaceRootInput);
  const destination = resolve(workspaceRoot, generatedPath);
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, await generateGoThemeContract(workspaceRoot), "utf8");
}

export async function verifyGoThemeContract(workspaceRootInput: string): Promise<{ readonly verified: true }> {
  const workspaceRoot = resolve(workspaceRootInput);
  const [expected, actual] = await Promise.all([
    generateGoThemeContract(workspaceRoot),
    readFile(resolve(workspaceRoot, generatedPath), "utf8"),
  ]);
  if (actual !== expected) {
    throw new Error("Go Theme CLI contract is stale. Run npm run go:theme-contract:build and commit the generated file.");
  }
  return { verified: true };
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (invokedPath === import.meta.url) {
  if (process.argv.includes("--check")) {
    await verifyGoThemeContract(process.cwd());
    process.stdout.write("Go Theme CLI contract is current.\n");
  } else {
    await writeGoThemeContract(process.cwd());
  }
}
